version: '3'

services:
  edge:
    build:
      context: .
      dockerfile: Dockerfile
    image: $REGISTRY_SERVER/iot-edge-device:latest
    volumes:
      - ./cert:/etc/iotedge/cert
    ports:
      - "5671:5671"
      - "8883:8883"
      - "443:443"
    privileged: true
    environment:
      TERM: xterm
      ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID
      ARM_CLIENT_ID: $ARM_CLIENT_ID
      ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET
      ARM_TENANT_ID: $ARM_TENANT_ID
      HUB: $HUB