version: '3'
services:
  edge:
    build: .
    image: $REGISTRY_SERVER/iot-edge-device:latest
    privileged: true
    environment:
      ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID
      ARM_CLIENT_ID: $ARM_CLIENT_ID
      ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET
      ARM_TENANT_ID: $ARM_TENANT_ID
      HUB: $HUB
