version: '3'
services:
  edge:
    build:
      context: .
      dockerfile: Dockerfile
    image: $REGISTRY_SERVER/iot-edge-device:latest
    deploy:
      replicas: 1
    privileged: true
    environment:
      TERM: xterm
      ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID
      ARM_CLIENT_ID: $ARM_CLIENT_ID
      ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET
      ARM_TENANT_ID: $ARM_TENANT_ID
      HUB: $HUB
